name: migrations
on: pull_request

jobs:
  did-migration-update:
    name: check if migration
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - name: Checkout sentry
        uses: actions/checkout@v2

      - name: Match migration files
        uses: getsentry/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml

  modified-migration:
    name: check modified migration
    runs-on: ubuntu-20.04
    timeout-minutes: 4
    needs: did-migration-update
    steps:
      - name: Failure because of modified migration
        shell: bash
        if: needs.changes.outputs.migrations_modified == 'true'
        run: |
          echo "We do not allow modifying migrations. Use GH admin if you still need to merge." && exit 1

  sql:
    name: Generate SQL
    runs-on: ubuntu-20.04
    timeout-minutes: 8
    needs: did-migration-update

    steps:
      # Checkout master to run all merged migrations.
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Set python version output
        id: python-version
        run: |
          echo "::set-output name=python-version::$(cat .python-version)"

      # Until GH composite actions can use `uses`, we need to setup python here
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ steps.python-version.outputs.python-version }}

      - name: Setup pip
        uses: ./.github/actions/setup-pip
        id: pip

      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip.outputs.pip-cache-dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup sentry env
        uses: ./.github/actions/setup-sentry
        id: setup

      - name: Apply migrations
        run: |
          sentry upgrade --noinput

      # Checkout the current ref
      - uses: actions/checkout@v1
        with:
          clean: false

      - name: Get changed migration files
        id: file
        run: |
          echo $(git diff --diff-filter=A --name-only origin/master HEAD)
          echo "::set-output name=added::$(git diff --diff-filter=A --name-only origin/master HEAD | grep 'src/sentry/migrations/')"

      - name: Generate SQL for migration
        uses: getsentry/action-migrations@v1.0.7
        env:
          SENTRY_LOG_LEVEL: ERROR
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          migration: ${{ steps.file.outputs.added }}
